### ISSUE TITLE
解答错误:  [leetcode 93]  里面的答案错乱为 Add Sum

### ISSUE THREAD

**Issue by zhaolion** [kylesliu/awesome-golang-leetcode#100]
题目: Restore-IP-Addresses
实际回答: https://github.com/kylesliu/awesome-golang-leetcode/tree/master/src/0093.Restore-IP-Addresses 里面 README 和回答都是 `Add Sum`

**Comment by kylesliu** [comment]
> 题目: Restore-IP-Addresses
> 实际回答: https://github.com/kylesliu/awesome-golang-leetcode/tree/master/src/0093.Restore-IP-Addresses 里面 README 和回答都是 `Add Sum`

你可以提个PR修改

**Comment by kylesliu** [comment]
已经修改

**Comment by zhaolion** [comment]
Cool :)
